"""Shared validator release/package version constants."""

VALIDATOR_RELEASE_VERSION = "20260430.post3"
VALIDATOR_PACKAGE_VERSION = "20260430.post3"

__all__ = ["VALIDATOR_PACKAGE_VERSION", "VALIDATOR_RELEASE_VERSION"]
