"""Shared validator release/package version constants."""

VALIDATOR_RELEASE_VERSION = "20260514.post1"
VALIDATOR_PACKAGE_VERSION = "20260514.post1"

__all__ = ["VALIDATOR_PACKAGE_VERSION", "VALIDATOR_RELEASE_VERSION"]
